package model;

import dataStructureGraph.Edge;
import dataStructureGraph.SimpleGraph;
import dataStructureGraph.SimpleWeightedGraph;
import dataStructureGraph.Vertex;

public class IcesiMap {

	private SimpleGraph<Integer> g;
	private SimpleWeightedGraph<Integer> w;

	public void createIcesiSimpleMap() {
		g = new SimpleGraph<>();
		Vertex<Integer> v = new Vertex<>(1, "");
		g.addVertex(v);
		for(int c=2;c<137;c++) {
			if(c==135) {
				v= new Vertex<Integer>(c, "El Saman");
			}else if(c==26) {
				v= new Vertex<Integer>(c, "Auditorios");
			}else if(c==31) {
				v= new Vertex<Integer>(c, "Cafeteria principal");
			}else if(c==48) {
				v= new Vertex<Integer>(c, "K");
			}else if(c==69) {
				v= new Vertex<Integer>(c, "Expo");
			}else if(c==96) {
				v= new Vertex<Integer>(c, "F");
			}else if(c==55) {
				v= new Vertex<Integer>(c, "H");
			}else if(c==57) {
				v= new Vertex<Integer>(c, "Bienestar (I)");
			}else if(c==61) {
				v= new Vertex<Integer>(c, "J");
			}else if(c==100) {
				v= new Vertex<Integer>(c, "D");
			}else if(c==114) {
				v= new Vertex<Integer>(c, "E");
			}else if(c==112) {
				v= new Vertex<Integer>(c, "Futbol 2");
			}else if(c==109) {
				v= new Vertex<Integer>(c, "Futbol 1");
			}else if(c==123) {
				v= new Vertex<Integer>(c, "N");
			}else if(c==26) {
				v= new Vertex<Integer>(c, "O");
			}else if(c==98) {
				v= new Vertex<Integer>(c, "C");
			}else if(c==13) {
				v= new Vertex<Integer>(c, "B");
			}else if(c==14) {
				v= new Vertex<Integer>(c, "O");
			}else if(c==12) {
				v= new Vertex<Integer>(c, "Biblioteca");
			}else if(c==92) {
				v= new Vertex<Integer>(c, "G");
			}else {
				v= new Vertex<Integer>(c, "");
			}
			g.addVertex(v);
		}
		g.addVertex(v);
		Edge<Integer> e = new Edge<>(9.62, g.getNodes().get(1), g.getNodes().get(2));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(2), g.getNodes().get(3));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(3), g.getNodes().get(9));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(1), g.getNodes().get(4));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(4), g.getNodes().get(135));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(131), g.getNodes().get(2));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(131), g.getNodes().get(5));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(3), g.getNodes().get(5));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(4), g.getNodes().get(6));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(6), g.getNodes().get(7));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(6), g.getNodes().get(10));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(7), g.getNodes().get(131));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(7), g.getNodes().get(12));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(7), g.getNodes().get(8));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(8), g.getNodes().get(5));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(8), g.getNodes().get(11));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(10), g.getNodes().get(13));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(10), g.getNodes().get(35));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(11), g.getNodes().get(19));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(11), g.getNodes().get(14));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(12), g.getNodes().get(13));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(12), g.getNodes().get(14));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(13), g.getNodes().get(36));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(13), g.getNodes().get(16));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(14), g.getNodes().get(15));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(15), g.getNodes().get(19));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(15), g.getNodes().get(17));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(15), g.getNodes().get(29));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(15), g.getNodes().get(23));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(7), g.getNodes().get(20));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(7), g.getNodes().get(22));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(18), g.getNodes().get(20));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(20), g.getNodes().get(21));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(22), g.getNodes().get(23));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(22), g.getNodes().get(25));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(23), g.getNodes().get(24));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(23), g.getNodes().get(26));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(24), g.getNodes().get(31));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(24), g.getNodes().get(33));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(24), g.getNodes().get(27));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(25), g.getNodes().get(27));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(26), g.getNodes().get(27));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(16), g.getNodes().get(19));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(16), g.getNodes().get(38));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(19), g.getNodes().get(12));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(19), g.getNodes().get(28));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(28), g.getNodes().get(29));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(28), g.getNodes().get(32));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(29), g.getNodes().get(31));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(31), g.getNodes().get(32));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(32), g.getNodes().get(34));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(33), g.getNodes().get(43));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(34), g.getNodes().get(46));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(35), g.getNodes().get(36));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(36), g.getNodes().get(37));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(37), g.getNodes().get(38));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(37), g.getNodes().get(98));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(38), g.getNodes().get(98));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(38), g.getNodes().get(39));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(39), g.getNodes().get(40));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(39), g.getNodes().get(52));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(40), g.getNodes().get(49));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(40), g.getNodes().get(42));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(40), g.getNodes().get(41));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(41), g.getNodes().get(50));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(42), g.getNodes().get(51));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(42), g.getNodes().get(52));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(43), g.getNodes().get(45));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(45), g.getNodes().get(47));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(46), g.getNodes().get(48));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(46), g.getNodes().get(47));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(47), g.getNodes().get(50));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(47), g.getNodes().get(70));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(47), g.getNodes().get(71));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(50), g.getNodes().get(51));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(50), g.getNodes().get(63));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(51), g.getNodes().get(63));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(51), g.getNodes().get(62));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(52), g.getNodes().get(53));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(53), g.getNodes().get(54));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(54), g.getNodes().get(55));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(54), g.getNodes().get(56));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(55), g.getNodes().get(60));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(56), g.getNodes().get(57));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(57), g.getNodes().get(58));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(58), g.getNodes().get(59));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(59), g.getNodes().get(60));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(60), g.getNodes().get(61));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(60), g.getNodes().get(62));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(61), g.getNodes().get(62));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(62), g.getNodes().get(119));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(62), g.getNodes().get(129));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(63), g.getNodes().get(64));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(64), g.getNodes().get(65));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(65), g.getNodes().get(66));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(65), g.getNodes().get(132));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(66), g.getNodes().get(67));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(66), g.getNodes().get(94));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(67), g.getNodes().get(68));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(67), g.getNodes().get(95));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(68), g.getNodes().get(69));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(69), g.getNodes().get(75));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(69), g.getNodes().get(76));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(70), g.getNodes().get(71));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(70), g.getNodes().get(73));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(70), g.getNodes().get(74));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(71), g.getNodes().get(72));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(72), g.getNodes().get(73));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(73), g.getNodes().get(74));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(74), g.getNodes().get(75));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(75), g.getNodes().get(76));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(76), g.getNodes().get(82));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(77), g.getNodes().get(78));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(77), g.getNodes().get(87));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(78), g.getNodes().get(79));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(79), g.getNodes().get(85));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(79), g.getNodes().get(80));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(80), g.getNodes().get(81));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(81), g.getNodes().get(82));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(83), g.getNodes().get(90));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(84), g.getNodes().get(85));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(84), g.getNodes().get(86));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(84), g.getNodes().get(90));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(85), g.getNodes().get(91));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(86), g.getNodes().get(87));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(87), g.getNodes().get(88));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(88), g.getNodes().get(89));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(90), g.getNodes().get(92));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(92), g.getNodes().get(93));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(94), g.getNodes().get(95));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(94), g.getNodes().get(97));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(95), g.getNodes().get(96));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(96), g.getNodes().get(97));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(98), g.getNodes().get(99));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(99), g.getNodes().get(100));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(100), g.getNodes().get(101));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(100), g.getNodes().get(102));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(101), g.getNodes().get(105));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(102), g.getNodes().get(103));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(102), g.getNodes().get(116));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(103), g.getNodes().get(104));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(104), g.getNodes().get(105));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(104), g.getNodes().get(114));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(104), g.getNodes().get(105));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(105), g.getNodes().get(106));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(106), g.getNodes().get(107));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(106), g.getNodes().get(114));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(107), g.getNodes().get(108));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(107), g.getNodes().get(111));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(108), g.getNodes().get(109));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(108), g.getNodes().get(110));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(109), g.getNodes().get(112));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(110), g.getNodes().get(111));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(110), g.getNodes().get(112));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(111), g.getNodes().get(113));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(114), g.getNodes().get(115));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(115), g.getNodes().get(116));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(115), g.getNodes().get(117));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(117), g.getNodes().get(118));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(119), g.getNodes().get(120));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(120), g.getNodes().get(121));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(121), g.getNodes().get(122));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(122), g.getNodes().get(123));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(122), g.getNodes().get(124));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(122), g.getNodes().get(128));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(124), g.getNodes().get(125));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(124), g.getNodes().get(127));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(125), g.getNodes().get(126));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(127), g.getNodes().get(134));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(128), g.getNodes().get(129));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(128), g.getNodes().get(135));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(130), g.getNodes().get(133));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(130), g.getNodes().get(135));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(132), g.getNodes().get(133));
		g.addEdge(e);
		e = new Edge<>(1, g.getNodes().get(134), g.getNodes().get(135));
		g.addEdge(e);
		g.getNodes().remove(0);
		g.getNodes().remove(30);
		g.getNodes().remove(44);
	}

	public SimpleGraph<Integer> returnSimpleGraph() {
		return g;
	}

	public void createIcesiSimpleWeightedMap() {
		w = new SimpleWeightedGraph<>();
		Vertex<Integer> v = new Vertex<>(0, "null");
		w.addVertex(v);
		v = new Vertex<>(1, "");
		w.addVertex(v);
		for(int c=2;c<137;c++) {
			if(c==135) {
				v= new Vertex<Integer>(c, "El Saman");
			}else if(c==26) {
				v= new Vertex<Integer>(c, "Auditorios");
			}else if(c==31) {
				v= new Vertex<Integer>(c, "Cafeteria principal");
			}else if(c==48) {
				v= new Vertex<Integer>(c, "K");
			}else if(c==69) {
				v= new Vertex<Integer>(c, "Expo");
			}else if(c==96) {
				v= new Vertex<Integer>(c, "F");
			}else if(c==55) {
				v= new Vertex<Integer>(c, "H");
			}else if(c==57) {
				v= new Vertex<Integer>(c, "Bienestar (I)");
			}else if(c==61) {
				v= new Vertex<Integer>(c, "J");
			}else if(c==100) {
				v= new Vertex<Integer>(c, "D");
			}else if(c==114) {
				v= new Vertex<Integer>(c, "E");
			}else if(c==112) {
				v= new Vertex<Integer>(c, "Futbol 2");
			}else if(c==109) {
				v= new Vertex<Integer>(c, "Futbol 1");
			}else if(c==123) {
				v= new Vertex<Integer>(c, "N");
			}else if(c==26) {
				v= new Vertex<Integer>(c, "O");
			}else if(c==98) {
				v= new Vertex<Integer>(c, "C");
			}else if(c==13) {
				v= new Vertex<Integer>(c, "B");
			}else if(c==14) {
				v= new Vertex<Integer>(c, "O");
			}else if(c==12) {
				v= new Vertex<Integer>(c, "Biblioteca");
			}else if(c==92) {
				v= new Vertex<Integer>(c, "G");
			}else {
				v= new Vertex<Integer>(c, "");
			}
			g.addVertex(v);
		}
		w.addVertex(v);
		Edge<Integer> e = new Edge<>(9.62, w.getNodes().get(1), w.getNodes().get(2));
		w.addEdge(e);
		e = new Edge<>(9.65, w.getNodes().get(2), w.getNodes().get(3));
		w.addEdge(e);
		e = new Edge<>(22.59, w.getNodes().get(3), w.getNodes().get(9));
		w.addEdge(e);
		e = new Edge<>(9.64, w.getNodes().get(1), w.getNodes().get(4));
		w.addEdge(e);
		e = new Edge<>(12.98, w.getNodes().get(4), w.getNodes().get(135));
		w.addEdge(e);
		e = new Edge<>(12.32, w.getNodes().get(131), w.getNodes().get(2));
		w.addEdge(e);
		e = new Edge<>(11.67, w.getNodes().get(131), w.getNodes().get(5));
		w.addEdge(e);
		e = new Edge<>(8.96, w.getNodes().get(3), w.getNodes().get(5));
		w.addEdge(e);
		e = new Edge<>(9.61, w.getNodes().get(4), w.getNodes().get(6));
		w.addEdge(e);
		e = new Edge<>(9.62, w.getNodes().get(6), w.getNodes().get(7));
		w.addEdge(e);
		e = new Edge<>(8.49, w.getNodes().get(6), w.getNodes().get(10));
		w.addEdge(e);
		e = new Edge<>(12.49, w.getNodes().get(7), w.getNodes().get(131));
		w.addEdge(e);
		e = new Edge<>(17.76, w.getNodes().get(7), w.getNodes().get(12));
		w.addEdge(e);
		e = new Edge<>(9.61, w.getNodes().get(7), w.getNodes().get(8));
		w.addEdge(e);
		e = new Edge<>(6, w.getNodes().get(8), w.getNodes().get(5));
		w.addEdge(e);
		e = new Edge<>(8.46, w.getNodes().get(8), w.getNodes().get(11));
		w.addEdge(e);
		e = new Edge<>(12.48, w.getNodes().get(10), w.getNodes().get(13));
		w.addEdge(e);
		e = new Edge<>(20.04, w.getNodes().get(10), w.getNodes().get(35));
		w.addEdge(e);
		e = new Edge<>(12, w.getNodes().get(11), w.getNodes().get(19));
		w.addEdge(e);
		e = new Edge<>(12, w.getNodes().get(11), w.getNodes().get(14));
		w.addEdge(e);
		e = new Edge<>(12.8, w.getNodes().get(12), w.getNodes().get(13));
		w.addEdge(e);
		e = new Edge<>(15.18, w.getNodes().get(12), w.getNodes().get(14));
		w.addEdge(e);
		e = new Edge<>(20.04, w.getNodes().get(13), w.getNodes().get(36));
		w.addEdge(e);
		e = new Edge<>(32.6, w.getNodes().get(13), w.getNodes().get(16));
		w.addEdge(e);
		e = new Edge<>(12.61, w.getNodes().get(14), w.getNodes().get(15));
		w.addEdge(e);
		e = new Edge<>(12.62, w.getNodes().get(15), w.getNodes().get(19));
		w.addEdge(e);
		e = new Edge<>(26.48, w.getNodes().get(15), w.getNodes().get(17));
		w.addEdge(e);
		e = new Edge<>(35.01, w.getNodes().get(15), w.getNodes().get(29));
		w.addEdge(e);
		e = new Edge<>(24.97, w.getNodes().get(15), w.getNodes().get(23));
		w.addEdge(e);
		e = new Edge<>(18.25, w.getNodes().get(7), w.getNodes().get(20));
		w.addEdge(e);
		e = new Edge<>(12.67, w.getNodes().get(7), w.getNodes().get(22));
		w.addEdge(e);
		e = new Edge<>(9.74, w.getNodes().get(18), w.getNodes().get(20));
		w.addEdge(e);
		e = new Edge<>(21.19, w.getNodes().get(20), w.getNodes().get(21));
		w.addEdge(e);
		e = new Edge<>(13.42, w.getNodes().get(22), w.getNodes().get(23));
		w.addEdge(e);
		e = new Edge<>(34.065, w.getNodes().get(22), w.getNodes().get(25));
		w.addEdge(e);
		e = new Edge<>(20.645, w.getNodes().get(23), w.getNodes().get(24));
		w.addEdge(e);
		e = new Edge<>(21.41, w.getNodes().get(23), w.getNodes().get(26));
		w.addEdge(e);
		e = new Edge<>(28.15, w.getNodes().get(24), w.getNodes().get(31));
		w.addEdge(e);
		e = new Edge<>(14.11, w.getNodes().get(24), w.getNodes().get(33));
		w.addEdge(e);
		e = new Edge<>(34.065, w.getNodes().get(24), w.getNodes().get(27));
		w.addEdge(e);
		e = new Edge<>(34.065, w.getNodes().get(25), w.getNodes().get(27));
		w.addEdge(e);
		e = new Edge<>(28.77, w.getNodes().get(26), w.getNodes().get(27));
		w.addEdge(e);
		e = new Edge<>(12.1, w.getNodes().get(16), w.getNodes().get(19));
		w.addEdge(e);
		e = new Edge<>(40.17, w.getNodes().get(16), w.getNodes().get(38));
		w.addEdge(e);
		e = new Edge<>(37.74, w.getNodes().get(19), w.getNodes().get(12));
		w.addEdge(e);
		e = new Edge<>(14.93, w.getNodes().get(19), w.getNodes().get(28));
		w.addEdge(e);
		e = new Edge<>(13.79, w.getNodes().get(28), w.getNodes().get(29));
		w.addEdge(e);
		e = new Edge<>(26.54, w.getNodes().get(28), w.getNodes().get(32));
		w.addEdge(e);
		e = new Edge<>(6.51, w.getNodes().get(29), w.getNodes().get(31));
		w.addEdge(e);
		e = new Edge<>(26.82, w.getNodes().get(31), w.getNodes().get(32));
		w.addEdge(e);
		e = new Edge<>(13.95, w.getNodes().get(32), w.getNodes().get(34));
		w.addEdge(e);
		e = new Edge<>(43.62, w.getNodes().get(33), w.getNodes().get(43));
		w.addEdge(e);
		e = new Edge<>(12.15, w.getNodes().get(34), w.getNodes().get(46));
		w.addEdge(e);
		e = new Edge<>(12.48, w.getNodes().get(35), w.getNodes().get(36));
		w.addEdge(e);
		e = new Edge<>(9.63, w.getNodes().get(36), w.getNodes().get(37));
		w.addEdge(e);
		e = new Edge<>(29.78, w.getNodes().get(37), w.getNodes().get(38));
		w.addEdge(e);
		e = new Edge<>(4.83, w.getNodes().get(37), w.getNodes().get(98));
		w.addEdge(e);
		e = new Edge<>(30.24, w.getNodes().get(38), w.getNodes().get(98));
		w.addEdge(e);
		e = new Edge<>(23.35, w.getNodes().get(38), w.getNodes().get(39));
		w.addEdge(e);
		e = new Edge<>(22.69, w.getNodes().get(39), w.getNodes().get(40));
		w.addEdge(e);
		e = new Edge<>(44.8, w.getNodes().get(39), w.getNodes().get(52));
		w.addEdge(e);
		e = new Edge<>(15.25, w.getNodes().get(40), w.getNodes().get(49));
		w.addEdge(e);
		e = new Edge<>(45.13, w.getNodes().get(40), w.getNodes().get(42));
		w.addEdge(e);
		e = new Edge<>(10.91, w.getNodes().get(40), w.getNodes().get(41));
		w.addEdge(e);
		e = new Edge<>(9.14, w.getNodes().get(41), w.getNodes().get(50));
		w.addEdge(e);
		e = new Edge<>(19.09, w.getNodes().get(42), w.getNodes().get(51));
		w.addEdge(e);
		e = new Edge<>(22.84, w.getNodes().get(42), w.getNodes().get(52));
		w.addEdge(e);
		e = new Edge<>(8.13, w.getNodes().get(43), w.getNodes().get(45));
		w.addEdge(e);
		e = new Edge<>(34.36, w.getNodes().get(45), w.getNodes().get(47));
		w.addEdge(e);
		e = new Edge<>(17.41, w.getNodes().get(46), w.getNodes().get(48));
		w.addEdge(e);
		e = new Edge<>(22.12, w.getNodes().get(46), w.getNodes().get(47));
		w.addEdge(e);
		e = new Edge<>(29.58, w.getNodes().get(47), w.getNodes().get(50));
		w.addEdge(e);
		e = new Edge<>(10.97, w.getNodes().get(47), w.getNodes().get(70));
		w.addEdge(e);
		e = new Edge<>(19.73, w.getNodes().get(47), w.getNodes().get(71));
		w.addEdge(e);
		e = new Edge<>(47.98, w.getNodes().get(50), w.getNodes().get(51));
		w.addEdge(e);
		e = new Edge<>(44.84, w.getNodes().get(50), w.getNodes().get(63));
		w.addEdge(e);
		e = new Edge<>(45.13, w.getNodes().get(51), w.getNodes().get(63));
		w.addEdge(e);
		e = new Edge<>(40.29, w.getNodes().get(51), w.getNodes().get(62));
		w.addEdge(e);
		e = new Edge<>(17.2, w.getNodes().get(52), w.getNodes().get(53));
		w.addEdge(e);
		e = new Edge<>(8.01, w.getNodes().get(53), w.getNodes().get(54));
		w.addEdge(e);
		e = new Edge<>(51.14, w.getNodes().get(54), w.getNodes().get(55));
		w.addEdge(e);
		e = new Edge<>(14.77, w.getNodes().get(54), w.getNodes().get(56));
		w.addEdge(e);
		e = new Edge<>(22.82, w.getNodes().get(55), w.getNodes().get(60));
		w.addEdge(e);
		e = new Edge<>(10.21, w.getNodes().get(56), w.getNodes().get(57));
		w.addEdge(e);
		e = new Edge<>(11.28, w.getNodes().get(57), w.getNodes().get(58));
		w.addEdge(e);
		e = new Edge<>(11.92, w.getNodes().get(58), w.getNodes().get(59));
		w.addEdge(e);
		e = new Edge<>(33.52, w.getNodes().get(59), w.getNodes().get(60));
		w.addEdge(e);
		e = new Edge<>(14.69, w.getNodes().get(60), w.getNodes().get(61));
		w.addEdge(e);
		e = new Edge<>(25.75, w.getNodes().get(60), w.getNodes().get(62));
		w.addEdge(e);
		e = new Edge<>(12.77, w.getNodes().get(61), w.getNodes().get(62));
		w.addEdge(e);
		e = new Edge<>(35.92, w.getNodes().get(62), w.getNodes().get(119));
		w.addEdge(e);
		e = new Edge<>(24.05, w.getNodes().get(62), w.getNodes().get(129));
		w.addEdge(e);
		e = new Edge<>(66.05, w.getNodes().get(63), w.getNodes().get(64));
		w.addEdge(e);
		e = new Edge<>(15.83, w.getNodes().get(64), w.getNodes().get(65));
		w.addEdge(e);
		e = new Edge<>(56.86, w.getNodes().get(65), w.getNodes().get(66));
		w.addEdge(e);
		e = new Edge<>(87.64, w.getNodes().get(65), w.getNodes().get(132));
		w.addEdge(e);
		e = new Edge<>(40, w.getNodes().get(66), w.getNodes().get(67));
		w.addEdge(e);
		e = new Edge<>(51.69, w.getNodes().get(66), w.getNodes().get(94));
		w.addEdge(e);
		e = new Edge<>(13.71, w.getNodes().get(67), w.getNodes().get(68));
		w.addEdge(e);
		e = new Edge<>(51.29, w.getNodes().get(67), w.getNodes().get(95));
		w.addEdge(e);
		e = new Edge<>(19.12, w.getNodes().get(68), w.getNodes().get(69));
		w.addEdge(e);
		e = new Edge<>(50.26, w.getNodes().get(69), w.getNodes().get(75));
		w.addEdge(e);
		e = new Edge<>(54.68, w.getNodes().get(69), w.getNodes().get(76));
		w.addEdge(e);
		e = new Edge<>(18.11, w.getNodes().get(70), w.getNodes().get(71));
		w.addEdge(e);
		e = new Edge<>(5.53, w.getNodes().get(70), w.getNodes().get(73));
		w.addEdge(e);
		e = new Edge<>(29.53, w.getNodes().get(70), w.getNodes().get(74));
		w.addEdge(e);
		e = new Edge<>(11.63, w.getNodes().get(71), w.getNodes().get(72));
		w.addEdge(e);
		e = new Edge<>(11.05, w.getNodes().get(72), w.getNodes().get(73));
		w.addEdge(e);
		e = new Edge<>(35.09, w.getNodes().get(73), w.getNodes().get(74));
		w.addEdge(e);
		e = new Edge<>(45.27, w.getNodes().get(74), w.getNodes().get(75));
		w.addEdge(e);
		e = new Edge<>(20.4, w.getNodes().get(75), w.getNodes().get(76));
		w.addEdge(e);
		e = new Edge<>(28.73, w.getNodes().get(76), w.getNodes().get(82));
		w.addEdge(e);
		e = new Edge<>(9.09, w.getNodes().get(77), w.getNodes().get(78));
		w.addEdge(e);
		e = new Edge<>(74.11, w.getNodes().get(77), w.getNodes().get(87));
		w.addEdge(e);
		e = new Edge<>(19.33, w.getNodes().get(78), w.getNodes().get(79));
		w.addEdge(e);
		e = new Edge<>(32.38, w.getNodes().get(79), w.getNodes().get(85));
		w.addEdge(e);
		e = new Edge<>(45.27, w.getNodes().get(79), w.getNodes().get(80));
		w.addEdge(e);
		e = new Edge<>(15, w.getNodes().get(80), w.getNodes().get(81));
		w.addEdge(e);
		e = new Edge<>(18.5, w.getNodes().get(81), w.getNodes().get(82));
		w.addEdge(e);
		e = new Edge<>(24.05, w.getNodes().get(83), w.getNodes().get(90));
		w.addEdge(e);
		e = new Edge<>(15.77, w.getNodes().get(84), w.getNodes().get(85));
		w.addEdge(e);
		e = new Edge<>(20.66, w.getNodes().get(84), w.getNodes().get(86));
		w.addEdge(e);
		e = new Edge<>(24.14, w.getNodes().get(84), w.getNodes().get(90));
		w.addEdge(e);
		e = new Edge<>(10.89, w.getNodes().get(85), w.getNodes().get(91));
		w.addEdge(e);
		e = new Edge<>(17.34, w.getNodes().get(86), w.getNodes().get(87));
		w.addEdge(e);
		e = new Edge<>(50.36, w.getNodes().get(87), w.getNodes().get(88));
		w.addEdge(e);
		e = new Edge<>(70.85, w.getNodes().get(88), w.getNodes().get(89));
		w.addEdge(e);
		e = new Edge<>(14.19, w.getNodes().get(90), w.getNodes().get(92));
		w.addEdge(e);
		e = new Edge<>(19.11, w.getNodes().get(92), w.getNodes().get(93));
		w.addEdge(e);
		e = new Edge<>(13.22, w.getNodes().get(94), w.getNodes().get(95));
		w.addEdge(e);
		e = new Edge<>(37.55, w.getNodes().get(94), w.getNodes().get(97));
		w.addEdge(e);
		e = new Edge<>(13.98, w.getNodes().get(95), w.getNodes().get(96));
		w.addEdge(e);
		e = new Edge<>(3.4, w.getNodes().get(96), w.getNodes().get(97));
		w.addEdge(e);
		e = new Edge<>(13.7, w.getNodes().get(98), w.getNodes().get(99));
		w.addEdge(e);
		e = new Edge<>(15.07, w.getNodes().get(99), w.getNodes().get(100));
		w.addEdge(e);
		e = new Edge<>(15.85, w.getNodes().get(100), w.getNodes().get(101));
		w.addEdge(e);
		e = new Edge<>(18.91, w.getNodes().get(100), w.getNodes().get(102));
		w.addEdge(e);
		e = new Edge<>(39.76, w.getNodes().get(101), w.getNodes().get(105));
		w.addEdge(e);
		e = new Edge<>(12.48, w.getNodes().get(102), w.getNodes().get(103));
		w.addEdge(e);
		e = new Edge<>(18.3, w.getNodes().get(102), w.getNodes().get(116));
		w.addEdge(e);
		e = new Edge<>(10.75, w.getNodes().get(103), w.getNodes().get(104));
		w.addEdge(e);
		e = new Edge<>(8.99, w.getNodes().get(104), w.getNodes().get(105));
		w.addEdge(e);
		e = new Edge<>(5.5, w.getNodes().get(104), w.getNodes().get(114));
		w.addEdge(e);
		e = new Edge<>(12.18, w.getNodes().get(104), w.getNodes().get(105));
		w.addEdge(e);
		e = new Edge<>(9.45, w.getNodes().get(105), w.getNodes().get(106));
		w.addEdge(e);
		e = new Edge<>(9.15, w.getNodes().get(106), w.getNodes().get(107));
		w.addEdge(e);
		e = new Edge<>(10.04, w.getNodes().get(106), w.getNodes().get(114));
		w.addEdge(e);
		e = new Edge<>(7.87, w.getNodes().get(107), w.getNodes().get(108));
		w.addEdge(e);
		e = new Edge<>(51.45, w.getNodes().get(107), w.getNodes().get(111));
		w.addEdge(e);
		e = new Edge<>(48.25, w.getNodes().get(108), w.getNodes().get(109));
		w.addEdge(e);
		e = new Edge<>(54.41, w.getNodes().get(108), w.getNodes().get(110));
		w.addEdge(e);
		e = new Edge<>(69.21, w.getNodes().get(109), w.getNodes().get(112));
		w.addEdge(e);
		e = new Edge<>(12.58, w.getNodes().get(110), w.getNodes().get(111));
		w.addEdge(e);
		e = new Edge<>(30.63, w.getNodes().get(110), w.getNodes().get(112));
		w.addEdge(e);
		e = new Edge<>(17.44, w.getNodes().get(111), w.getNodes().get(113));
		w.addEdge(e);
		e = new Edge<>(21.6, w.getNodes().get(114), w.getNodes().get(115));
		w.addEdge(e);
		e = new Edge<>(29.4, w.getNodes().get(115), w.getNodes().get(116));
		w.addEdge(e);
		e = new Edge<>(17.69, w.getNodes().get(115), w.getNodes().get(117));
		w.addEdge(e);
		e = new Edge<>(8.71, w.getNodes().get(117), w.getNodes().get(118));
		w.addEdge(e);
		e = new Edge<>(25.93, w.getNodes().get(119), w.getNodes().get(120));
		w.addEdge(e);
		e = new Edge<>(21.72, w.getNodes().get(120), w.getNodes().get(121));
		w.addEdge(e);
		e = new Edge<>(11.11, w.getNodes().get(121), w.getNodes().get(122));
		w.addEdge(e);
		e = new Edge<>(12.75, w.getNodes().get(122), w.getNodes().get(123));
		w.addEdge(e);
		e = new Edge<>(26.48, w.getNodes().get(122), w.getNodes().get(124));
		w.addEdge(e);
		e = new Edge<>(35.32, w.getNodes().get(122), w.getNodes().get(128));
		w.addEdge(e);
		e = new Edge<>(24.01, w.getNodes().get(124), w.getNodes().get(125));
		w.addEdge(e);
		e = new Edge<>(13.34, w.getNodes().get(124), w.getNodes().get(127));
		w.addEdge(e);
		e = new Edge<>(13, w.getNodes().get(125), w.getNodes().get(126));
		w.addEdge(e);
		e = new Edge<>(20.55, w.getNodes().get(127), w.getNodes().get(134));
		w.addEdge(e);
		e = new Edge<>(28.69, w.getNodes().get(128), w.getNodes().get(129));
		w.addEdge(e);
		e = new Edge<>(16.43, w.getNodes().get(128), w.getNodes().get(135));
		w.addEdge(e);
		e = new Edge<>(30.04, w.getNodes().get(130), w.getNodes().get(133));
		w.addEdge(e);
		e = new Edge<>(36.9, w.getNodes().get(130), w.getNodes().get(135));
		w.addEdge(e);
		e = new Edge<>(39.53, w.getNodes().get(132), w.getNodes().get(133));
		w.addEdge(e);
		e = new Edge<>(14.76, w.getNodes().get(134), w.getNodes().get(135));
		w.addEdge(e);
		w.getNodes().remove(0);
		w.getNodes().remove(30);
		w.getNodes().remove(44);
	}


public SimpleWeightedGraph<Integer> returnSimpleWeightedGraph() {
	return w;
}
}
